# Specify base image 
FROM node:16-alpine as builder

# Create working directory
WORKDIR /user/app

# Copy files to Container
COPY ./package.json ./

# Run install command
RUN npm install

COPY . .

# Default command
RUN npm run build

# Run Phase
FROM node:16-alpine 
WORKDIR /user/app
COPY ./package.json ./
RUN npm install
COPY --from=builder /user/app/dist .
CMD ["node", "server.js"]
